### ISSUE TITLE
make universal hs product dimension

### ISSUE THREAD

**Issue by alexandersimoes** [observatory-economic-complexity/oec-etl#25]
The goal here is to make a universal HS product dimension that would include the superset of all HS classifications: 92/96/02/07/12/17. The names will be the most recent for which the code exists. Individual fact tables could then maintain references to the original product name and classification.

**Comment by MarcioPorto** [comment]
@alexandersimoes based on our decision to use the latest revision HS name for each ID, I noticed that the HS names for some products end up being pretty long since we had done some work on shortening only the HS92 revision names (as far as I know).

Just wanted to note that here in case we decide we want to revise this approach.
